services:
  app-admin:
    build:
      context: ./app-admin
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mongo
    environment:
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      PAYLOAD_PUBLIC_DATABASE_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017
      PAYLOAD_PUBLIC_ADMIN_URL: http://localhost:3001
      PAYLOAD_PUBLIC_MAIN_URL: http://localhost:3000
    restart: always

  app-main:
    build:
      context: ./app-main
      dockerfile: Dockerfile
      args:
        - ADMIN_URL=http://localhost:3001
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - ASTRA_DB_APPLICATION_TOKEN=${ASTRA_DB_APPLICATION_TOKEN}
        - ASTRA_DB_ENDPOINT=${ASTRA_DB_ENDPOINT}
        - ASTRA_DB_NAMESPACE=${ASTRA_DB_NAMESPACE}
    ports:
      - '3000:3000'
    restart: always

  redis:
    image: redis:6.0
    command: ["redis-server", "--appendonly", "yes", "--bind", "127.0.0.1"]
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  data: