FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app

CMD ["celery", "-A", "app.celery_config.celery_app", "worker", "--loglevel=info"]
